### ISSUE TITLE
Update schedule

### ISSUE THREAD

**Issue by mdlincoln** [MuseumofModernArt/collection#10]
I understand from the README that the goal is to update this data extract regularly to reflect changes in the upstream CMS. Has there been any movement towards formalizing this update process?

**Comment by smoore4moma** [comment]
Hello @mdlincoln.  I am the DBA at MoMA.  Getting the data as a csv file is fairly trivial.  So is publishing it.  I've been meaning to write a job using the API to automatically publish it, and that has been the part I haven't been able to devote time to.  We are constantly updating the upstream CMS and the csv needs to reflect that.  It is on our list to do shortly.  FYI.

**Comment by mdlincoln** [comment]
:+1:  I look forward to seeing the solution you come up with!

**Comment by momadm** [comment]
Hi, We are currently working on a set of scripts for updating the data on a periodic basis but hit some snags concerning the size of the datasets. We'll close this issue when the automatic updates are in place. Thank you for your continued interest.

**Comment by clinejj** [comment]
This information will now be updated on a weekly basis.
