### ISSUE TITLE
The DOI badge/reference is broken

### ISSUE THREAD

**Issue by dblock** [MuseumofModernArt/collection#15]
The one I found is [MOMA Collection of Artsits](https://zenodo.org/record/46902?ln=en). The README references something else that no longer exists.

[![DOI](https://zenodo.org/badge/doi/10.5281/zenodo.46902.svg)](http://dx.doi.org/10.5281/zenodo.46902)

**Comment by momadm** [comment]
Hi, Sorry for the inconvenience, I've fixed the problem and released an updated version.
