### ISSUE TITLE
Glossary of terms

### ISSUE THREAD

**Issue by sassanh** [MuseumofModernArt/collection#17]
Hi,

Thanks for sharing this valuable database for easy use. I'm wondering if you're willing to share glossary of terms too (https://www.moma.org/learn/moma_learning/glossary) I know it's not that hard to extract a json from that page myself, but an official release from Museum is more valuable and I can rely on updates, etc.

**Comment by clinejj** [comment]
Hello, unfortunately that data is kept separate from what we use to generate the collection dataset and we would not be able to publish separately. We have also migrated that glossary to https://www.moma.org/collection/terms.
