### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by evemikebowman** [MuseumofModernArt/collection#18]
When clicking on the download button for this file the data is presented in the browser rather than downloading as a .csv file.

**Comment by plongyear** [comment]
Hi @evemikebowman,

When the browser opens the csv, you can click `File` -> `Save Page As...` in your browser (or whatever your browser's equivalent is for saving files) to download the csv.

**Comment by evemikebowman** [comment]
Hi Peter,

thanks for getting back to me.  I've also found out that if I install
Github desktop and clone the MOMA collection to my computer then the csv
file is downloaded as part of that process.

Regards

Mike Bowman

**Comment by plongyear** [comment]
Good to know!
