### ISSUE TITLE
HTTPS thumbnail URLs

### ISSUE THREAD

**Issue by mitar** [MuseumofModernArt/collection#24]
It looks like all thumbnail URLs are HTTP which then get redirected to HTTPS. Could they be updated to be HTTPS in JSON already?

**Comment by mitar** [comment]
I see that HTTP URLs do not get redirected back to HTTPS. Is this the fix?

**Comment by clinejj** [comment]
Apologies - we have merged in the code that fixes this but it won't be updated until the next update (scheduled for Tueday)

**Comment by clinejj** [comment]
This has been addressed in the latest release: https://github.com/MuseumofModernArt/collection/releases/tag/2024-02-20

**Comment by mitar** [comment]
Thanks!
