### ISSUE TITLE
Numerical date (year) of the work

### ISSUE THREAD

**Issue by mitar** [MuseumofModernArt/collection#28]
On the website (in its search engine) I see that works have a numerical date (year) you can filter on. But in data here date is an arbitrary string. So there is already a cleaned version? Could it be added?

**Comment by clinejj** [comment]
The information that we include in this dataset is the most accurate data we have. Particularly for artworks where there is not as clear information, the search on the website uses an approximate date for that filter. We'd rather include the most accurate data in this set than the approximation.

**Comment by mitar** [comment]
Hm, but there are also examples of dates like:

* `"Date": "(1946)"`
* `"Date": "published 1893"`

Why are those not just `1946` and `1893`?

**Comment by clinejj** [comment]
That might be a good question to send to collection@moma.org - my team is mostly the maintainer of the tooling that uploads the dataset, and that gets a bit more into how we categorize the collection which that team can better handle.
