### ISSUE TITLE
"Title" header in CSV file contains 'ZERO WIDTH NO-BREAK SPACE' (U+FEFF)

### ISSUE THREAD

**Issue by straup** [MuseumofModernArt/collection#3]
For example:

{
  "Medium": "Lift ground aquatint, aquatint, and soft ground etching, printed in black",
  "Dimensions": "plate  4 5/8 x 5 1/2\" (11.8 x 13.9 cm)",
  "Classification": "Illustrated Book",
  "Artist": "Bill Jensen",
  "URL": "",
  "CuratorApproved": "N",
  "CreditLine": "Gift of Emily Fisher Landau",
  "Date": "1989-1994",
  "Department": "Prints & Illustrated Books",
  "MoMANumber": "595.1994.5",
  "ArtistBio": "(American, born 1945)",
  "DateAcquired": "1994-11-08",
  "\ufeffTitle": "Headpiece (folio 18) from POSTCARDS FROM TRAKL",
  "ObjectID": "19407"
}

**Comment by straup** [comment]
Presumably because this?

https://github.com/MuseumofModernArt/collection/commit/b54db532ba80d295ff53135e5485a6b87b16380d

**Comment by rikvanmechelen** [comment]
@straup are you still seeing this? If so, how did you get/generate this json?
