### ISSUE TITLE
l instead of 1

### ISSUE THREAD

**Issue by yanofsky** [MuseumofModernArt/collection#6]
On three works by Pierre Petit the date listed is `l860s ?`

(moma numbers 367.1981, 368.1981, and 369.1981)

Seeing how he was alive 1832-1909 I assume the date is supposed to be `1860s ?`

Correct? I'll make this a pull request if that is the case.

**Comment by rikvanmechelen** [comment]
I think you are right, I will pass this on so it can get corrected in the underlaying database. Some future export will then include these changes.
