### ISSUE TITLE
License Clarification: Is this really a public domain work? 

### ISSUE THREAD

**Issue by MrTomWhite** [MuseumofModernArt/collection#7]
Howdy! 

This is a superb dataset and it's super exciting to see the Museum of Modern Art share it with the world. 

I was wondering if you could help clarify the way your usage guidelines on the readme concerning derivative works and the license of this work interact. IANAL and it's confusing to me. :frowning:  

Background
======

In particular: [Emphasis mine]

>"Do not misrepresent the dataset
Do not mislead others or misrepresent the dataset or its source. ... *Whenever you transform, translate or otherwise modify the dataset, you must make it clear that the resulting information has been modified by you. If you enrich or otherwise modify the dataset, consider publishing the derived dataset without reuse restrictions.*"

And the license: [Emphasis mine]
>"To the greatest extent permitted by, but not in contravention of,
applicable law, *Affirmer hereby overtly, fully, permanently, irrevocably and
unconditionally waives, abandons, and surrenders all of Affirmer's Copyright
and Related Rights* and associated claims and causes of action, whether now
known or unknown (including existing as well as future claims and causes of
action), in the Work (i) in all territories worldwide, (ii) for the maximum
duration provided by applicable law or treaty (including future time
extensions), (iii) in any current or future medium and for any number of
copies, and (iv) for any purpose whatsoever, including without limitation
commercial, advertising or promotional purposes (the "Waiver")."

I was considering playing with this dataset, but it seems like a plausible interpretation that: 

- Visualizing the data or reporting regression results is a translation or transformation of the data
- I could optionally follow the guideline that mandates that "you must make it clear that the resulting information has been modified by you."; thus I would need to modify my derivative work to include proper attribution to MoMA *and* myself. This at least constrains me from releasing any derivative work anonymously.
- I could optionally follow the guideline: "If you enrich or otherwise modify the dataset, consider publishing the derived dataset without reuse restrictions." This probably means I can't consider a CC BY SA NC license. :-1: :crying_cat_face: (It's one of my favorites)

Neither of these guidelines make sense for a work that has been given to the public domain. 

The first clause seems to address citation/plagiarism, which is a very important concern. Attribution of *the original work* is key for avoiding plagiarism. 
[Plagiarism.org](http://www.plagiarism.org/ask-the-experts/faq/) or many university citation guides, like [this one](http://guides.temple.edu/c.php?g=77882&p=515489) explain this further. 

However, beyond the academic context, there's no requirement that a derivative work contain the author's original name. In fact, [some](https://www.reddit.com/wiki/faq#wiki_is_posting_personal_information_ok.3F) [authors](https://en.wikipedia.org/wiki/Whistleblower) may [choose](https://en.wikipedia.org/wiki/Mark_Twain) to avoid the use of their real name on the internet. 

The second clause encouraging me to avoid one of my favorite creative commons licenses seems misplaced. If I make a derivative work from a public domain work, the derivative work (as independent from the dataset itself) can be copyrighted however I please. The dataset remains in the public domain.

>"The copyright in a derivative work covers only the additions,
changes, or other new material appearing for the first time
in the work. Protection does not extend to any preexisting
material, that is, previously published or previously registered
works or works in the public domain or owned by a
third party."-
[copyright.gov](http://copyright.gov/circs/circ14.pdf)

Coda 
=====

"The public domain comprises a body of knowledge and innovation over which no person or other legal entity can assert proprietary rights" - https://www1.villanova.edu/villanova/generalcounsel/copyright/edumaterial/plagiarism.html

Proposal
=====

1. MoMA should figure out if they intend to assert any proprietary rights over this data set. I contend this includes, at a minimum, picking a stance on attribution rights and the license of derivative works. 
2. If MoMA wishes to assert no proprietary rights of the work, there should be no normative statements about derivative works in the readme. I can submit a pull request to this repository that removes those if you'd like. 
3. If MoMA wishes to assert proprietary rights over the dataset, they should select an appropriate license. Creative Commons licenses are free culture licenses, so they're a great place for museums to start looking. http://creativecommons.org/choose/  I can submit a pull request that adds an appropriate free culture license if you'd like. 

Thank you so much for your time and thank you for sharing your data!

**Comment by foeromeo** [comment]
Hello Tom,

It was our intention to release this data into the public domain. The additional notes express some preferences but they do not in any way override the CC0 license. You are therefore free to release your work anonymously and publish it using your preferred CC BY SA NC license.

You raise a good point about anonymity and I will look at changing the wording of our guidelines from
"Whenever you transform, translate or otherwise modify the dataset, you must make it clear that the resulting information has been modified by you" to "Whenever you transform, translate or otherwise modify the dataset, you must make it clear that the resulting information has been modified."

I hope this addresses your concerns.

Best regards,
Fiona
